In [1]:
import numpy as np    #importing the whole package
from numpy.linalg import inv    #importing a specific function for matrix inversion 

In [2]:
matrix = np.array([[4.0, 2.0, 4.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

print("Matrix:")
print(matrix)

inv_mat = inv(matrix)
print("Inverse:")
print(inv_mat)

Matrix:
[[4. 2. 4.]
 [4. 5. 6.]
 [7. 8. 9.]]
Inverse:
[[ 0.25       -1.16666667  0.66666667]
 [-0.5        -0.66666667  0.66666667]
 [ 0.25        1.5        -1.        ]]


In [3]:
!pip install rich

Looking in indexes: https://oksuzd:****@onsart-01/artifactory/api/pypi/yr-python/simple


In [4]:
from rich import inspect
inspect(inv, help=True)

╭─────────────────── <function inv at 0x000002586F182340> ───────────────────╮
│ def inv(a):                                                                │
│                                                                            │
│ Compute the inverse of a matrix.                                           │
│                                                                            │
│ Given a square matrix `a`, return the matrix `ainv` satisfying             │
│ ``a @ ainv = ainv @ a = eye(a.shape[0])``.                                 │
│                                                                            │
│ Parameters                                                                 │
│ ----------                                                                 │
│ a : (..., M, M) array_like                                                 │
│     Matrix to be inverted.                                                 │
│                                                                            │
│ Returns                                                                    │
│ -------                                                                    │
│ ainv : (..., M, M) ndarray or matrix                                       │
│     Inverse of the matrix `a`.                                             │
│                                                                            │
│ Raises                                                                     │
│ ------                                                                     │
│ LinAlgError                                                                │
│     If `a` is not square or inversion fails.                               │
│                                                                            │
│ See Also                                                                   │
│ --------                                                                   │
│ scipy.linalg.inv : Similar function in SciPy.                              │
│ numpy.linalg.cond : Compute the condition number of a matrix.              │
│ numpy.linalg.svd : Compute the singular value decomposition of a matrix.   │
│                                                                            │
│ Notes                                                                      │
│ -----                                                                      │
│                                                                            │
│ .. versionadded:: 1.8.0                                                    │
│                                                                            │
│ Broadcasting rules apply, see the `numpy.linalg` documentation for         │
│ details.                                                                   │
│                                                                            │
│ If `a` is detected to be singular, a `LinAlgError` is raised. If `a` is    │
│ ill-conditioned, a `LinAlgError` may or may not be raised, and results may │
│ be inaccurate due to floating-point errors.                                │
│                                                                            │
│ References                                                                 │
│ ----------                                                                 │
│ .. [1] Wikipedia, "Condition number",                                      │
│        https://en.wikipedia.org/wiki/Condition_number                      │
│                                                                            │
│ Examples                                                                   │
│ --------                                                                   │
│ >>> import numpy as np                                                     │
│ >>> from numpy.linalg import inv                                           │
│ >>> a = np.array([[1., 2.], [3., 4.]])          